name: Deploy JustTheDocs & Wasm Playground

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Compilar WebAssembly
        run: |
          mkdir -p web
          GOOS=js GOARCH=wasm go build -o web/main.wasm ./cmd/wasm
          cp $(go env GOROOT)/misc/wasm/wasm_exec.js web/

      - name: Setup Ruby (Para Jekyll/JustTheDocs)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: './docs'

      - name: Construir JustTheDocs
        working-directory: './docs'
        run: |
          bundle install
          bundle exec jekyll build -d ../_site

      - name: Unir Documentación con Playground Web
        run: |
          mkdir -p _site/web
          cp -r web/* _site/web/
          mkdir -p _site/data/images
          cp -r data/images/* _site/data/images/
          touch _site/.nojekyll

      - name: Subir artefacto a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
